services:
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres-db
    volumes:
      - ./webapp/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
  backend:
    build: ./webapp/backend
    image: alchikinov/webapp-backend:latest
    container_name: backend
    # health check option
    # healthcheck:
      # test: ["CMD-SHELL", "curl -f localhost:5050/api/data"]
      # interval: 10s
      # timeout: 2s
      # retries: 5
      # start_period: 10s
    ports:
      - 5050:5050
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: 0.5
        reservations:
          memory: 15M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 10s
    depends_on:
      - postgres-db
  api-tests:
    build:
      context: ./api-tests
      dockerfile: Dockerfile-runner
    image: alchikinov/api-tests-runner:latest
    container_name: api-tests

    # hardcoded option, bad example
    # command:  sh -c "sleep 10 && cucumber PLATFORM=LOCAL"
    # depends_on:
      # - backend

    # option with health check for backend service
    # command: cucumber PLATFORM=LOCAL
    # depends_on:
    #   backend:
    #     condition: service_healthy  

    # option with wait script
    # script inserted into api-tests Docker base file
    environment:
      - WAIT_HOSTS=postgres-db:5432,backend:5050
    command:  sh -c "/wait && cucumber PLATFORM=LOCAL"
    depends_on:
      - backend
