apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-dev
  labels:
    app: frontend-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
      - name: frontend-dev
        image: alchikinov/webapp-frontend-multi-stage:latest
        ports:
        - containerPort: 80