name: Webapp CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Build Backend application
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/build
        with:
          application: backend
          docker_image_tag: alchikinov/webapp-backend:$GITHUB_SHA
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
      - name: Build Frontend application
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/build
        with:
          application: frontend
          docker_image_tag: alchikinov/webapp-frontend-multi-stage:$GITHUB_SHA

  deploy-dev:
    name: Deploy Kubuernetes - DEV
    runs-on: self-hosted
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
      - name: Deploy Frontend
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: frontend-deployment-dev
          deployment_pod_name: frontend-dev
          docker_image_tag: alchikinov/webapp-frontend-multi-stage:$GITHUB_SHA
      - name : Deploy Backend
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/deploy
        with:
          deployment_name: backend-deployment-dev
          deployment_pod_name: backend-dev
          docker_image_tag: alchikinov/webapp-backend:$GITHUB_SHA

  test-dev:
    name: Run API Tests - DEV
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Run API Tests
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/test
        with:
          test_environment: DEV
