name: Webapp CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./.github/actions/build
        with:
          application: backend
          docker_image_tag: alchikinov/webapp-backend
          # - name: Build Backend Docker Image
      #   run: docker build -t alchikinov/webapp-backend ./webapp/backend  
      # - name: Pushing Docker Image to Docker Hub
      #   run: docker push alchikinov/webapp-backend

  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./.github/actions/build
        with:
          application: backend
          docker_image_tag: alchikinov/webapp-frontend-multi-stage
          # - name: Build Frontend Docker Image
      #   run: docker build -t alchikinov/webapp-frontend-multi-stage ./webapp/frontend  
      # - name: Pushing Docker Image to Docker Hub
      #   run: docker push alchikinov/webapp-frontend-multi-stage
  
  deploy-backened-dev:
    name: Delploy Backend to Kubernetes DEV
    runs-on: self-hosted
    needs: [build-backend]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-dev:
    name: Delploy Frontend to Kubernetes DEV
    runs-on: self-hosted
    needs: [build-frontend]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-dev:
    name: Run API Tests against DEV Backend
    runs-on: self-hosted
    needs: [deploy-backened-dev]
    steps:
      - run: echo "Running tests.."
  deploy-backened-stg:
    name: Delploy Backend to Kubernetes STG
    runs-on: self-hosted
    needs: [test-backend-dev]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-stg:
    name: Delploy Frontend to Kubernetes STG
    runs-on: self-hosted
    needs: [deploy-frontend-dev]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-stg:
    name: Run API Tests against PRD Backend
    runs-on: self-hosted
    needs: [deploy-backened-stg]
    steps:
      - run: echo "Running tests.."
  deploy-backened-prd:
    name: Delploy Backend to Kubernetes PRD
    runs-on: self-hosted
    needs: [test-backend-stg]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-prd:
    name: Delploy Frontend to Kubernetes PRD
    runs-on: self-hosted
    needs: [deploy-frontend-stg]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-prd:
    name: Run API Tests against PRD Backend
    runs-on: self-hosted
    needs: [deploy-backened-prd]
    steps:
      - run: echo "Running tests.."